name: Github Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Data da execução
        run: echo "A execução do workflow foi iniciada 14/09/2026."