name: Github Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        run: echo "The job was automatically triggered by a ${{ github.event}} event."
      - name: Data da execução
        run: echo "The workflow run was created at 14/09/2026."
      - name: terceiro step
        run: echo "o repositório que está sendo executado é o ${{github.repository}}."
       
      